language: cpp
sudo: required
dist: trusty

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.8']  
      sonarcloud:
        organization: "freeeyes-github"
        token:
          secure: "qzWDGQvGlJlBvJyG+jhAQXRU3K6n0tf+u6goSNMnW9K1/qkJLThO158V8o4N/Yu4JE5L7hIVlSUUuJbU6xEWWazm4x4rI4KGQ8z8K6F7Jm7kshpNybp8PzibkOiB7K2F8+adrk9bELeYGSA06UqlAtvSn5Q22GlFq+Zwlp8RYGFcZHNOaK0GGPPRu4xHdDMIBhpg5kwjEEpYbfWYmhJJRqNzkityhBxylvcCCnln6FDUpgRbIdCzntl2f5Ctp8ZA9zS5ZX/XMOIbtEePT8DisBQ6s0wMIjthBgEhI9om8yphNe8QYv8Y9kfcK+dvpOvm9RKXZrmzXBKgl2JEmp9vxYFLspQy0y4oVeM7l+7gPa6Bj3lpszbOhZZtHmoBQh7RETW5Fmg3ubKDi9+vGWx417k/JRjdGD8NHHDPDhcDSWCgx85y2UcpO1JUY1LoLl7pF6HAQkFG+Eb3wO7bogvgTd46QJixrmJu/kCC7bFVhKVGGpgRq1A4h4dkwfDvTw8w5zL74zd7AdghwfqihEq2PwfizADCoaszocgOg4kmqIsakuVaGE7r4fo4E4sShcb036OIQz2F6gJmLMgasTMG5E1s+K/j2m3QOZ2fLIyKm2/0rKbL9jYvtYf27FWpBKyPnyIKNegZSu7F/RDEGk2qMkIeK7iuV/4DsDXgJcXMiHk="
             
install:  
before_script:
  - eval "${MATRIX_EVAL}"
  - env
  - export CC_FOR_BUILD=$CC
  - export CXX_FOR_BUILD=$CXX
script:
  - pwd
    #make
    - cmake -E make_directory $TRAVIS_BUILD_DIR/Build/Linux
    - cd $TRAVIS_BUILD_DIR/Build/Linux
    - cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - cmake --build . --config $BUILD_TYPE

     
