name: PSS_ASIO_CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/Build/Linux

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/Build/Linux
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/Build/Linux
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    #- name: check path and run program
    #  working-directory: ${{github.workspace}}/Build/Linux  
    #  shell: bash
    #  run: |
    #    ls -l
    #    nohup ./pss_asio > pssout.file 2>&1 &
    #    sleep 10
    #    killall pss_asio

    - name: install google test
      working-directory: ${{github.workspace}}/tests
      shell: bash 
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make

    - name: run google test
      working-directory: ${{github.workspace}}/tests
      shell: bash 
      run: |
        apt list --installed | grep gtest
        cmake .
        cmake --build . --config debug
        ./test_pss_asio
    - name: make report
      working-directory: ${{github.workspace}}/tests
      shell: bash 
      run: |
        python google_test.py Test_Pss_Asio.xml
        ls -l

    - name: git add test html report
      working-directory: ${{github.workspace}}/tests
      shell: bash 
      run: | 
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add -f gtest_output.html
        git commit -m "[ci update]google test report"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}